openapi: 3.0.1
info:
  title: MooGold API
  description: This is the documentation of MooGold API. It is a JSON based API that
    enables you to connect to MooGold's digital gift card & direct top up inventory
    to enrich your current distribution system.
  termsOfService: https://moogold.com/terms-and-conditions/
  contact:
    email: sales@moogold.com
  x-logo:
    url: https://cdn.moogold.com/2021/09/moogold.svg
    altText: MooGold logo
    href: https://moogold.com
  version: '1.0'
externalDocs:
  description: Find out more about MooGold
  url: https://moogold.com
servers:
- url: https://moogold.com/wp-json/v1/api
- url: https://moogold.com/wp-json/v1/api
tags:
- name: Authentication
  description: "Authentication is required before using the MooGold API. Every API\
    \ method requires the same authentication process.\nIf you don't have a partner\
    \ ID or secret key, contact your account manager to obtain them. <br/><br/> Header:\n\
    1. Basic Auth:\n\n   Format in header: `Authorization: Basic <YOUR_BASIC_AUTH_HERE>`\n\
    \n   To generate the Basic Auth value, use this formula: `base64_encode(Username(Partner\
    \ ID) + \":\" + Password(Secret Key))`\n\n   Example: If your Username (Partner\
    \ ID) is `ABC` and Password (Secret Key) is `DEF`, the code will be: `base64_encode('ABC:DEF')`.\
    \ The result will be `QUJDOkRFRg==`.\n\n   Example in PHP:\n\n   ```\n   $username\
    \ = 'ABC';\n   $password = 'DEF';\n   $basic_auth = base64_encode($username .\
    \ ':' . $password);\n   ```\n\n   In this example, `$basic_auth` will contain\
    \ the value `QUJDOkRFRg==`.\n   You can also use a <a target=\"_blank\" href=\"\
    https://www.blitter.se/utils/basic-authentication-header-generator/\">website\
    \ generator</a> to generate the Basic Auth header.\n   <br/><br/>\n2. Auth Signature:\n\
    \n   Create an Auth header Signature using this formula: `hash_hmac('SHA256',\
    \ Payload + Current Timestamp + Path, YOUR_SECRET_HERE)`\n\n   Example in PHP:\n\
    \n   ```\n   $STRING_TO_SIGN = \"{'path':'order/order_detail','order_id':'952305'}123123123order/order_detail\"\
    ;\n   hash_hmac('SHA256', $STRING_TO_SIGN, 'YOURSECRETKEY');\n   ```\n   <br/><br/>\n\
    \n3. Timestamp:\n\n   Include the current timestamp in UNIX format (e.g., 1640855204)\
    \ as part of your request.\n\n   Example in PHP:\n   \n   ```\n   $timestamp =\
    \ time();\n   ```\n <br/>  \n Make sure to include all three headers (Basic Auth,\
    \ Auth Signature, and Timestamp) in your API requests for proper authentication.\n\
    \n Example JSON request with authentication headers:\n\n <br/>\n{<br/>\n    \"\
    url\": \"https://moogold.com/wp-json/v1/api/order/YOUR_ENDPOINT\",<br/>\n    \"\
    method\": \"POST\",<br/>\n    \"headers\": {<br/>\n    \"Authorization\": \"Basic\
    \ QUJDOkRFRg==\",<br/>\n    \"auth\": \"generated_auth_signature\",<br/>\n   \
    \ \"timestamp\": \"current_unix_timestamp\"<br/>\n },<br/>\n    \"data\": {<br/>\n\
    \    \"your_request_data\": \"goes_here\"<br/>\n }<br/>\n}<br/>\n<br/> This example\
    \ demonstrates how to include all the necessary authentication headers in your\
    \ JSON API request.\n\n<br/><br/> <img src=\"img/Postman_header_example.PNG\"\
    \ alt=\"postman_header_example\" />\n\nNote: Basic Auth is not added in the example\
    \ picture as it is already added in the Authorization tab in postman.<br/><br/>\
    \ SAMPLE CODE FOR PHP <a target=\"_blank\" href=\"phpsamplecode.txt\">Click Here</a><br/>\
    \ SAMPLE CODE FOR Python <a target=\"_blank\" href=\"python-samplecode.txt\">Click\
    \ Here</a><br/> SAMPLE CODE FOR JS <a target=\"_blank\" href=\"jssamplecode.txt\"\
    >Click Here</a><br/>   SAMPLE CODE FOR C# <a target=\"_blank\" href=\"cssamplecode.txt\"\
    >Click Here</a><br/>      \n"
- name: Order
  description: 'Everything Regarding Creating, Retrieving orders.


    **Note: An order is only finalized when marked as ''Refunded''. For refunds on
    orders with ''incorrect-details'' or other statuses, please contact Customer Service
    to process a wallet refund prior to issuing a return to the customer.**

    '
  externalDocs:
    description: ''
    url: http://moogold.com
- name: Product
  description: All product details and information.
  externalDocs:
    description: ''
    url: http://moogold.com
- name: User
  description: User
  externalDocs:
    description: ''
    url: http://moogold.com
paths:
  /order/create_order:
    post:
      tags:
      - Order
      summary: Create Order
      requestBody:
        description: Create an order in MooGold
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_order'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create_order_response_200'
        '403':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_403'
      callbacks:
        orderInProgress:
          '{Callback URL} Contact your account manager to add callback URL to your account':
            post:
              summary: Create Order (Callback)
              description: 'A callback is triggered every time there is a significant
                update to an Order''s status. This includes updates to statuses such
                as ''refunded'', ''incorrect-details'', or ''completed''. After receiving
                the callback, the user is required to reply as json shown in the example
                image below. If the API fails to reach, it will retry every minute
                for up to 100 times until a success response is received.

                ![Callback Response Example](img/callback-response-example.PNG)

                '
              requestBody:
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        status:
                          type: string
                          description: Status of the order, e.g., 'refunded', 'incorrect-details',
                            'completed'.
                          example: refunded
                        message:
                          type: string
                          description: Descriptive message about the order status.
                          example: Order has been refunded.
                        account_details:
                          type: object
                          description: Account details associated with the order.
                          properties:
                            Username:
                              type: string
                              example: Username
                            User ID:
                              type: string
                              example: test
                        order_id:
                          type: integer
                          description: Unique identifier for the order.
                          example: 6287222
                        total:
                          type: string
                          description: Total amount of the order.
                          example: '3.90'
      security:
      - BasicAuth:
        - username
        - password
      x-codegen-request-body-name: body
  /order/order_detail:
    post:
      tags:
      - Order
      summary: Order Detail
      requestBody:
        description: Retrieve an Order Detail in MooGold
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order_detail'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order_detail_response_200'
        '403':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_403'
      security:
      - BasicAuth:
        - username
        - password
      x-codegen-request-body-name: body
  /order/order_detail_partner_id:
    post:
      tags:
      - Order
      summary: Order Details (Partner Order ID)
      description: 'Get Order Details using Partner Order ID, you will need to set
        partner order id in the create order api in order to use this.        '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - path
              - partner_order_id
              properties:
                path:
                  type: string
                  description: API path, in this case - order/order_detail_partner_id
                  example: order/order_detail_partner_id
                partner_order_id:
                  type: string
                  description: Your partner order id.
                  example: '12345'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: string
                    description: The ID of the order
                    example: '3680513'
                  date_created:
                    type: object
                    properties:
                      date:
                        type: string
                        description: The date the order was created
                        example: '2023-03-09 23:45:31.000000'
                      timezone_type:
                        type: integer
                        description: The timezone type
                        example: 3
                      timezone:
                        type: string
                        description: The timezone
                        example: Asia/Kuala_Lumpur
                  order_status:
                    type: string
                    description: The status of the order
                    example: completed
                  item:
                    type: array
                    description: The items in the order
                    example:
                    - product: Garena Free Fire / Garena Free Fire (MAX) - 210 Diamonds
                      variation_id: 215571
                      quantity: 1
                      price: '9.13'
                      player_id: '12314123'
                      server_id: ''
                      voucher_code:
                      - 'Serial Number: 2407145348 Pin Code: 1053152474740245'
                      - 'Serial Number: 2407453150 Pin Code: 0666288108037346'
                      - ZCM7L-XHKFF-QW970
                    items:
                      type: object
                      properties:
                        product:
                          type: string
                          description: Product name
                        variation_id:
                          type: string
                          description: Product variation id
                        quantity:
                          type: string
                          description: The quantity of the product
                        price:
                          type: string
                          description: Product price
                        player_id:
                          type: string
                          description: Player ID / User ID / etc
                        server_id:
                          type: string
                          description: Server ID
                        voucher_code:
                          type: string
                          description: The voucher code for the order (if exists)
                  partner_order_id:
                    type: string
                    description: Partner Order ID
                    example: '12345'
        '403':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_403'
      headers:
        timestamp:
          description: The current timestamp in UNIX format
          schema:
            type: integer
            format: int64
        auth:
          description: The result of hashing the request with the secret key using
            SHA256
          schema:
            type: string
        Authorization:
          description: The result of base64-encoding the string `521626304147a868bc0da954205ad65:ceSBn1fI5u`
          schema:
            type: string
        Content-Type:
          description: The content type of the request body
          schema:
            type: string
            components: null
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  security:
  - BasicAuth:
    - username
    - password
  x-codegen-request-body-name: body
  /order/transaction_history:
    post:
      tags:
        - Order
      summary: Retrieve order transaction history
      description: |
        Fetches a list of past orders for a given customer, filtered by date range, status, and pagination options.
        Both `start_date` and `end_date` are required. The date format must be `YYYY-MM-DD`.
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - path
                - start_date
                - end_date
              properties:
                path:
                  type: string
                  example: "order/transaction_history"
                start_date:
                  type: string
                  format: date
                  example: "2025-07-01"
                  description: Start date in `YYYY-MM-DD` format
                end_date:
                  type: string
                  format: date
                  example: "2025-07-15"
                  description: End date in `YYYY-MM-DD` format
                status:
                  type: string
                  enum: [processing, completed, refunded]
                  example: "completed"
                  description: Optional order status filter
                page:
                  type: integer
                  example: 1
                  description: Page number (default = 1)
                limit:
                  type: integer
                  example: 20
                  description: Max results per page (default = 20, max = 100)
      responses:
        '200':
          description: Transaction history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  page:
                    type: integer
                    example: 1
                  limit:
                    type: integer
                    example: 20
                  orders:
                    type: array
                    items:
                      type: object
                      properties:
                        order_id:
                          type: integer
                          example: 12345
                        date_created:
                          type: string
                          example: "2025-07-10 14:23:00"
                        status:
                          type: string
                          example: "completed"
                        total:
                          type: string
                          example: "10.00"
                        currency:
                          type: string
                          example: "USD"
                        items:
                          type: array
                          items:
                            type: object
                            properties:
                              product:
                                type: string
                                example: "PUBG Mobile UC"
                              quantity:
                                type: integer
                                example: 1
                              price:
                                type: string
                                example: "10.00"
        '419':
          description: Missing or invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_419'
        '434':
          description: Limit exceeded (max 100)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_434'
        '435':
          description: Invalid status provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_435'
        '436':
          description: Start date cannot be after end date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_436'
        '437':
          description: Date range too large (max 30 days)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_437'
  /product/list_product:
    post:
      tags:
      - Product
      summary: List Product
      requestBody:
        description: List MooGold Products according to Product Category
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/list_product'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_product_response_200'
        '403':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_403'
      security:
      - BasicAuth:
        - username
        - password
      x-codegen-request-body-name: body
  /product/product_detail:
    post:
      tags:
      - Product
      summary: Product Detail
      requestBody:
        description: Get specific product detail
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product_detail'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product_detail_response_200'
        '403':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_403'
      security:
      - BasicAuth:
        - username
        - password
      x-codegen-request-body-name: body
  /product/server_list:
    post:
      tags:
      - Product
      summary: Server List
      requestBody:
        description: Get product server list (If available)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/server_list'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server_list_response_200'
        '403':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_403'
      security:
      - BasicAuth:
        - username
        - password
      x-codegen-request-body-name: body
  /product/validate:
    post:
      tags:
      - Product
      summary: Validate Product
      description: 'Validates a product using the provided data.

        '
      requestBody:
        description: Product validation request
        required:
        - data
        - path
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
                  description: API path, e.g., "product/validate"
                data:
                  required:
                  - product-id
                  type: object
                  properties:
                    product-id:
                      type: string
                      description: The product ID
                      example: 428075
                    User ID:
                      type: string
                      description: Dynamic String, call get Product Details API to
                        get the fields to enter. For example - <br/> "fields":[{"name":"User
                        ID","type":"string"},{"name":"Server","type":"string"}]} <br/>
                        Fields to add = 1. User ID 2. Server
                      example: 123123141
                    Server:
                      type: string
                      description: Dynamic String, call get Product Details API to
                        get the fields to enter. For example - <br/> "fields":[{"name":"User
                        ID","type":"string"},{"name":"Server","type":"string"}]} <br/>
                        Fields to add = 1. User ID 2. Server
                      example: Asia
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The status of the validation
                    example: true
                  message:
                    type: string
                    description: A message regarding the validation
                    example: Account has been validated.
                  username:
                    type: string
                    example: MooGold
        '419':
          description: Invalid Path
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_419'
      security:
      - BasicAuth: []
  /user/balance:
    post:
      tags:
      - User
      summary: Balance
      requestBody:
        description: Retrieve your current wallet balance
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/balance'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/balance_response_200'
        '403':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_403'
      security:
      - BasicAuth:
        - username
        - password
      x-codegen-request-body-name: body
  /user/reload_balance:
    post:
      tags:
      - User
      summary: Reload Balance
      requestBody:
        description: Reload your wallet balance using USDT-TRC20 payment gateway
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reload_balance'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reload_balance_response_200'
        '419':
          description: Invalid Path
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_419'
        '424':
          description: Invalid Payment Method
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_424'
        '425':
          description: Invalid Amount
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response_425'
      security:
      - BasicAuth: []
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          enum:
          - placed
          - approved
          - delivered
        complete:
          type: boolean
          default: false
      xml:
        name: Order
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Category
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          description: User Status
          format: int32
      xml:
        name: User
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Tag
    create_order:
      required:
      - data
      - path
      type: object
      properties:
        path:
          type: string
          description: URL path of the create order, in this case `order/create_order`
          example: order/create_order
          data:
            $ref: '#/components/schemas/data'
          xml:
            name: create_order
        data:
          required:
          - category
          - product-id
          - quantity
          type: object
          properties:
            category:
              type: integer
              example: '1'
              description: Either 1 (Direct Top Up) or 2 (eVouchers), this category
                is different from list_product apis category id.
            product-id:
              type: integer
              example: '215570'
              description: It is the variation_id of Product Details API. Call the
                Product Details API to get the variation_id of the product you want
                to purchase and put it here.
            quantity:
              type: integer
              example: '1'
            User ID:
              type: string
              description: Dynamic String, call get Product Details API to get the
                fields to enter. For example - <br/> "fields":[{"name":"User ID","type":"string"},{"name":"Server","type":"string"}]}
                <br/> Fields to add = 1. User ID 2. Server
              example: '12314123'
            Server:
              type: string
              description: Dynamic String, call get Product Details API to get the
                fields to enter. For example - <br/> "fields":[{"name":"User ID","type":"string"},{"name":"Server","type":"string"}]}
                <br/> Fields to add = 1. User ID 2. Server
              example: '3402'
        partnerOrderId:
          type: string
          description: Optional Field. Enter your partner order id to make sure duplicate
            order are not submitted. By entering Partner Order ID, there will also
            be a callback to your specific callback url, contact your account manager
            to get this enabled.
          example: MG-12345
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_order_response_200'
      '419':
        description: Invalid Path
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/error_response_419'
      '424':
        description: Invalid Payment Method
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/error_response_424'
      '425':
        description: Invalid Amount
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/error_response_425'
    create_order_response_200:
      type: object
      properties:
        status:
          type: boolean
          example: 'true'
          description: ''
        message:
          type: string
          example: Order has been created successfully
        account_details:
          type: object
          properties:
            player_id:
              type: string
              example: '12314123'
            server_id:
              type: string
              example: '1'
            order_id:
              type: string
              example: '952272'
      xml:
        name: create_order
    order_detail:
      required:
      - path
      - order_id
      type: object
      properties:
        path:
          type: string
          example: order/order_detail
        order_id:
          type: integer
          example: '10111111'
          description: Your MooGold.com Order ID.
    order_detail_response_200:
      type: object
      properties:
        order_id:
          type: integer
          example: '10111111'
          description: Your MooGold.com Order ID.
        date_created:
          type: string
          example: '2021-12-28 16:09:39'
        order_status:
          type: string
          example: processing
        item:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
                example: Garena Free Fire - 110 Diamonds
                description: Product Name
              variation_id:
                type: integer
                example: 215570
                description: Product variation id.
              quantity:
                type: integer
                example: 1
                description: Ordered Item Quantity
              price:
                type: string
                example: '1.01'
                description: Single product price.
              player_id:
                type: string
                example: '12314123'
                description: Player ID of the customer
              server_id:
                type: string
                example: '3402'
                description: Server ID of the customer.
              voucher_code:
                type: string
                example:
                - 'Serial Number: 2407145348 Pin Code: 1053152474740245'
                - 'Serial Number: 2407453150 Pin Code: 0666288108037346'
                - ZCM7L-XHKFF-QW970
                description: The voucher code for the order (if exists)
        total:
          type: string
          example: '1.01'
          description: Total price of the order.
    list_product:
      required:
      - path
      - category_id
      type: object
      properties:
        path:
          type: string
          example: product/list_product
        category_id:
          type: integer
          example: 50
          description: 'MooGold Category ID corresponding to the product category.
            The available categories are:

            - Direct-top up products: 50

            - Other Gift Cards: 51

            - Amazon Gift Cards: 1391

            - Apple Music: 1444

            - Garena Shells: 766

            - Google Play: 538

            - iTunes Gift Card: 2433

            - League of Legends: 1223

            - Netflix: 874

            - PSN: 765

            - Razer Gold: 451

            - Riot Access Code: 1261

            - Roblox: 3563

            - Spotify: 992

            - Steam: 993

            - Apex Legends: 2377

            - XBox Gift Card: 3154

            - Nintendo Gift Card: 3737

            - NetEase Pay: 3381

            - Astro Pay: 3351

            - Bilibili: 3075

            - iQIYI: 3382'
    list_product_response_200:
      type: array
      items:
        type: object
        properties:
          ID:
            type: string
            example: '332'
            description: Product ID
          post_title:
            type: string
            example: 'Ragnarok M: Eternal Love (SEA)'
            description: Product Name.
    product_detail:
      required:
      - path
      - product_id
      type: object
      properties:
        path:
          type: string
          example: product/product_detail
        product_id:
          type: integer
          example: 7847
          description: MooGold Product ID, listed in LIST_PRODUCT API
    product_detail_response_200:
      type: object
      properties:
        Product_Name:
          type: string
          example: Garena Free Fire
          description: MooGold Product Name
        Image_URL:
          type: string
          example: https://moogold.com/wp-content/uploads/2019/08/FreeFire-Garena.jpg
          description: Product Image
        Variation:
          type: array
          items:
            type: object
            properties:
              variation_name:
                type: string
                example: 110 Diamonds
                description: Variation Name
              variation_id:
                type: integer
                example: 215570
                description: Variation ID
              variation_price:
                type: double
                example: 0.75
                description: Variation Price
              stock_status:
                type: string
                example: instock
                description: Variation stock status, ex - instock, outofstock
    server_list:
      required:
      - path
      - product_id
      type: object
      properties:
        path:
          type: string
          example: product/server_list
        product_id:
          type: integer
          example: 37007
          description: MooGold Product ID
    server_list_response_200:
      type: object
      properties:
        MiskaTown(NA):
          type: string
          example: '500001'
          description: Product Server Name
        SandCastle(NA):
          type: string
          example: '500002'
          description: Product Server Name
        MouthSwamp(NA):
          type: string
          example: '500003'
          description: Product Server Name
        RedwoodTown(NA):
          type: string
          example: '500004'
          description: Product Server Name
        Obelisk(NA):
          type: string
          example: '500005'
          description: Product Server Name
        NewLand(NA):
          type: string
          example: '500006'
          description: Product Server Name
    balance:
      required:
      - path
      type: object
      properties:
        path:
          type: string
          example: user/balance
    balance_response_200:
      type: object
      properties:
        currency:
          type: string
          example: USD
          description: Wallet currency
        balance:
          type: string
          example: '832.21'
          description: Wallet balance
    reload_balance:
      type: object
      properties:
        path:
          type: string
          example: user/reload_balance
          description: The API endpoint path for reloading the balance.
        payment_method:
          type: string
          example: usdt-trc20-payment-gateway
          description: The payment method used for reloading the balance <br/>(Only
            USDT TRC20 supported at the moment, "usdt-trc20-payment-gateway")
        amount:
          type: string
          example: 1000.0
          description: The amount to be reloaded in the user's balance.
      required:
      - path
      - payment_method
      - amount
      example:
        path: user/reload_balance
        payment_method: usdt-trc20-payment-gateway
        amount: 1000.0
    reload_balance_response_200:
      type: object
      properties:
        order_id:
          type: integer
          example: 3914381
          description: The unique identifier for the order.
        payment_address:
          type: string
          example: TSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxsL
          description: The payment address to send the USDT.
        amount:
          type: string
          example: 1000.00 USDT
          description: The amount of USDT to be sent.
        wallet_currency:
          type: string
          example: USD
          description: The currency of the wallet to top up.
      example:
        order_id: 3914381
        payment_address: TSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxsL
        amount: 1.12 USDT
        wallet_currency: USD
    error_response:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    error_response_109:
      type: object
      properties:
        err_code:
          type: string
          example: '109'
        err_message:
          type: string
          example: Invalid Signature.
    error_response_110:
      type: object
      properties:
        err_code:
          type: string
          example: '110'
        err_message:
          type: string
          example: Error Occured, please try again.
    error_response_116:
      type: object
      properties:
        err_code:
          type: string
          example: '116'
        err_message:
          type: string
          example: One order only allow a maximum of 10 quantity.
    error_response_117:
      type: object
      properties:
        err_code:
          type: string
          example: '117'
        err_message:
          type: string
          example: Product is not available yet, please contact your account manager
            for more info.
    error_response_403:
      type: object
      properties:
        err_code:
          type: string
          example: '403'
        err_message:
          type: string
          example: User not found or your account is not authorized to access the
            requested resource.
    error_response_419:
      type: object
      properties:
        err_code:
          type: string
          example: '419'
        err_message:
          type: string
          example: The requested resource is missing required arguments.
    error_response_420:
      type: object
      properties:
        err_code:
          type: string
          example: '420'
        err_message:
          type: string
          example: Duplicate Partner Order ID provided.
    error_response_421:
      type: object
      properties:
        err_code:
          type: string
          example: '421'
        err_message:
          type: string
          example: Partner Order ID not found.
    error_response_422:
      type: object
      properties:
        err_code:
          type: string
          example: '422'
        err_message:
          type: string
          example: Either the Product ID is incorrect/ missing or the API for this
            particular product has not yet been authorized for use with your account.
    error_response_424:
      type: object
      properties:
        err_code:
          type: string
          example: '424'
        err_message:
          type: string
          example: Invalid Payment Method.
    error_response_425:
      type: object
      properties:
        err_code:
          type: string
          example: '425'
        err_message:
          type: string
          example: Invalid Amount.
    error_response_433:
      type: object
      properties:
        err_code:
          type: string
          example: '433'
        err_message:
          type: string
          example: IP not allowed, kindly contact your account manager to know more.
    error_response_1111:
      type: object
      properties:
        err_code:
          type: string
          example: '1111'
        err_message:
          type: string
          example: The API endpoint is accessible exclusively to members only. Contact
            your account manager for more info.
    error_response_118:
      type: object
      properties:
        err_code:
          type: string
          example: '118'
        err_message:
          type: string
          example: Product selected belongs to the blocked product list.
    error_response_418:
      type: object
      properties:
        err_code:
          type: string
          example: '418'
        err_message:
          type: string
          example: The specified API path is incorrect. Kindly verify that the URL
            corresponds with the API path that was specified.
    error_response_423:
      type: object
      properties:
        err_code:
          type: string
          example: '423'
        err_message:
          type: string
          example: Category ID is missing.
    error_response_426:
      type: object
      properties:
        err_code:
          type: string
          example: '426'
        err_message:
          type: string
          example: Timestamp is incorrect.
    error_response_434:
      type: object
      properties:
        err_code:
          type: string
          example: '434'
        err_message:
          type: string
          example: 'Out of limit, current limit: 100.'
    error_response_435:
      type: object
      properties:
        err_code:
          type: string
          example: '435'
        err_message:
          type: string
          example: 'Invalid status provided. Please choose between: completed, processing,
            refunded.'
    error_response_436:
      type: object
      properties:
        err_code:
          type: string
          example: '436'
        err_message:
          type: string
          example: Start date cannot be later than end date.
    error_response_437:
      type: object
      properties:
        err_code:
          type: string
          example: '437'
        err_message:
          type: string
          example: Date range too large, must be between 30 days.
    error_response_111:
      type: object
      properties:
        err_code:
          type: string
          example: '111'
        err_message:
          type: string
          example: Insufficient Balance, kindly reload your balance and try again.
    error_response_113:
      type: object
      properties:
        err_code:
          type: string
          example: '113'
        err_message:
          type: string
          example: Product ID is missing.
    error_response_114:
      type: object
      properties:
        err_code:
          type: string
          example: '114'
        err_message:
          type: string
          example: Product Out of Stock, kindly contact account manager for more info.
  securitySchemes:
    BasicAuth:
      type: http
      scheme: Basic
    HTTP Header 1:
      type: apiKey
      in: header
      name: timestamp
      description: 'Enter the current timestamp, ex: 1640855204<br/><br/>You are required
        to add them in every of your request.'
    ApiKeyAuth:
      type: apiKey
      in: header
      name: auth
      description: 'Auth header generation: <br/><br/> hash_hmac(''SHA256'', Payload
        + Current Timestamp + Path, YOUR_SECRET_HERE)<br/><br/>Example: <br/><br/>$STRING_TO_SIGN
        = ''{''path'':''order/order_detail'',''order_id'': ''952305''}''123123123''path'':
        ''order/order_detail'''';<br/><br/>hash_hmac(''SHA256'', $STRING_TO_SIGN,
        ''YOURSECRETKEY''); <br/><br/>You are required to add them in every of your
        request.<br/><br/>Contact your account manager to get your secret key.'
